language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'cd(Pkg.dir("InverseLaplace")); include(joinpath("docs", "make.jl"))'
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("InverseLaplace")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
